-- Migration: Create invitacion table if missing
-- This migration creates a minimal invitacion table expected by the app and some auxiliary indexes.
-- Run: psql -d <db> -f migrations/002_create_invitacion_table.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public.invitacion (
  id_invitacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evento INTEGER NOT NULL,
  id_invitado INTEGER,
  nombre_invitado character varying NOT NULL,
  email character varying NOT NULL,
  telefono character varying,
  codigo_unico character varying,
  numero_acompanantes integer DEFAULT 0,
  mensaje_personalizado text,
  categoria character varying,
  restricciones_alimentarias text,
  estado character varying DEFAULT 'pendiente',
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_enviado timestamp without time zone,
  enviado boolean DEFAULT false
);

-- Basic constraints / indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_invitacion_codigo_unico ON public.invitacion (codigo_unico);
CREATE INDEX IF NOT EXISTS idx_invitacion_id_evento ON public.invitacion (id_evento);
CREATE INDEX IF NOT EXISTS idx_invitacion_id_invitado ON public.invitacion (id_invitado);

-- Optional FK constraints if referenced tables exist (will fail if they don't)
-- Add with caution: these are commented out; enable only if your DB has tables 'evento' and 'invitado'
-- ALTER TABLE public.invitacion ADD CONSTRAINT fk_invitacion_evento FOREIGN KEY (id_evento) REFERENCES public.evento(id_evento);
-- ALTER TABLE public.invitacion ADD CONSTRAINT fk_invitacion_invitado FOREIGN KEY (id_invitado) REFERENCES public.invitado(id_invitado);

COMMIT;
